import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Walmart notion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
    modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode; // Remove the ? to make it required
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex">
          {modal}
          {children}
        </div>
      </body>
    </html>
  );
}